version: '2'
services:
  web:
    build: .
    command: node index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - ./log:/usr/src/app/log
      - ./keystore:/usr/src/app/keystore
    ports:
      - "3000:3000"
